### ISSUE TITLE
Consider not filtering out properties that are explicitely set to undefined

### ISSUE THREAD

**Issue by lehni** [justmoon/node-extend#38]
There are use-cases in which it makes sense to set a property to `undefined` and still expect it to be copied. `Object.assign()` does not filter out such properties, either.

What's the reason for them to be filtered in node-extend?

**Comment by Mijago** [comment]
I know, it's late but.. 
I guess the if-clause is the answer to your question.

74: `// Don't bring in undefined values`
75: `} else if (typeof copy !== 'undefined') {`

Therefore, your undefined objects are just ignored.

**Comment by ljharb** [comment]
This follows the api of `$.extend` from jQuery, and won't deviate from it.

I recommend using [`Object.assign`](https://npmjs.com/object.assign) anyways, since it's now built into the language.

**Comment by danielo515** [comment]
This is a normal feature. You should be explicit about this and recommend other alternatives if you care about real merging with right precedence.

Regards

**Comment by ljharb** [comment]
@danielo515 I'm not able to understand your sentence. Can you restate it?

**Comment by danielo515** [comment]
Sure. 

I mean that when merging two objects the ones at the right usually takes precedence. If any of them has a value set to undefined it should take precedence over the previous ones. 
That is a behavior that I found on several implementations of deep copy, and I think it is normal to expect that behavior. Because this is not the default behavior of this library you should make it more prominent on the documentation.

**Comment by ljharb** [comment]
Ah, I understand what this issue is about now.

`Object.assign` does do what you mean - in other words, `Object.assign({}, { value: 3 }, { value: undefined })` will result in `{ value: undefined }`.

However, this module is exclusively to mirror jQuery's "extend" function, so that's the behavior it will preserve.

I recommend https://npmjs.com/object.assign if you want an official polyfill for the native language feature.

**Comment by danielo515** [comment]
> However, this module is exclusively to mirror jQuery's "extend" function, so that's the behavior it will preserve.
> 
> I recommend https://npmjs.com/object.assign if you want an official polyfill for the native language feature.

That exact advice is what I expect to be more noticeable. Since this module is just called extend, it could lead to confusion. I know that the very first sentence is that it mirrors JQuery's extend function, but for people who is not familiar with JQuery it means nothing. A small explanation of the unexpected behaviors would be nice, and of course your recommendation for another polyfill 

Thanks and regards
