### ISSUE TITLE
update eslint rules

### ISSUE THREAD

**Issue by palinchak** [justmoon/node-extend#42]
replace rule "no-empty-label" to "no-labels"

**Comment by ljharb** [comment]
I'm not sure what you're referring to?

**Comment by palinchak** [comment]
ellint remove rule "no-empty-label" after update to version 2.0

**Comment by ljharb** [comment]
The rules are correct for the version of eslint currently in package.json. If you're running into that error, you might be improperly using a global eslint instead of a local one - you should never have a globally installed eslint.

I've updated everything to the latest in 760d6be0d834fcfdb9f56a5126446d7e5a258be8
